### ISSUE TITLE
Hi having this issue while trying to use it in eclipse

### ISSUE THREAD

**Issue by reddyalice** [TehLeo/junion#2] opened 2018-11-15 12:49 UTC
Errors occurred during the build.
Errors running builder 'Java Builder' on project 'i-ON'.
Status ERROR: theleo.jstruct.plugin.ecl code=2 Error exit val 1: Error: Could not find or load main class theleo.jstruct.plugin.SourceCompiler null

**Comment by TehLeo** [comment] 2018-11-18 22:08
Is this the first time you have used the eclipse plugin or does it work in different project?

**Comment by reddyalice** [comment] 2018-11-18 22:41
I tried on other projects too awhile ago but I gave up after same problems this time I wanted to make it work and thats why I wrote

**Comment by reddyalice** [comment] 2018-11-18 22:46
Also it doesnt work on different projects or any eclipse project I try it on

**Comment by TehLeo** [comment] 2018-11-19 15:47
Which eclipse installation are you using?

Have you also followed the installation steps written here (https://tehleo.github.io/junion/install.html) or followed the video. The video shows the installation on eclipse oxygen.

It works for me fine on eclipse oxygen, guess it's time to test it on newer eclipse versions and see if it gets broken.

**Comment by TehLeo** [comment] 2018-11-19 16:12
Okay, I have tested it on new eclipse and it is working fine. 

Basically what your error tells is that it cannot find SourceCompiler class, which is located in junionc1.1.jar.

You have missed step 5 or 6 of the installation tutorial:
```
5. In .junion property file, set property compileLibs= path to junionc<version>.jar
6. Instead of step 5. you can add library junionc<version>.jar directly to your classpath. However it is not a runtime dependency.
```

**Comment by reddyalice** [comment] 2018-11-19 19:52
> Okay, I have tested it on new eclipse and it is working fine.
> 
> Basically what your error tells is that it cannot find SourceCompiler class, which is located in junionc1.1.jar.
> 
> You have missed step 5 or 6 of the installation tutorial:
> 
> ```
> 5. In .junion property file, set property compileLibs= path to junionc<version>.jar
> 6. Instead of step 5. you can add library junionc<version>.jar directly to your classpath. However it is not a runtime dependency.
> ```

I tried step 5, I followed up your instructions and watch the video 
can this be because of windows

**Comment by reddyalice** [comment] 2018-11-19 20:01
Alright after failing in 2 different windows PCs it worked on a linux desktop :|

**Comment by reddyalice** [comment] 2018-11-19 20:07
uh it failed in linux too x.x I am not getting what I am doing wrong I am following instructions step by step

**Comment by TehLeo** [comment] 2018-11-20 15:45
make sure the path to the junionc1.1.jar is correct.

Did you try step 6 instead? simply add junionc1.1.jar to your classpath as a library.

**Comment by ghost** [comment] 2018-12-03 11:26
I've the same problem as Kode.

Followed step by step your guide (and also watched your video tutorial):
* Installed the Eclipse Plugin
* Added junion1.1.jar to Build Path
* Set Forbidden Reference to Warning
* Created .junion file and defined compileLibs variabile with a correct path
* Created .generated_src_junion directory and added to the Build Path as Source Folder 

But I meet the following problems:
- "Status ERROR: theleo.jstruct.plugin.ecl code=2 Error exit val 1 (and so on...)" if I create a .junion file with an absolute path to junionc1.1.jar. Path also doesn't have any blank spaces.
- Same error if I add jstructc1.1.jar in Build Path and create a .junion file without defining or leaving empty compileLibs variable. Moreover, the .junion file is empty the first time I create it, but it's filled with all the variables after I build my project.
- Compilation completed successfully but "Not compiled with jstruct" Exception is raised if I attempt to define a Struct. That happens if I add jstructc1.1.jar as a library in Build Path and no .junion file is created

Working on Windows 10 1809, Eclipse 18-09 and JDK 1.8.0.192 chosen for my project

**Comment by TehLeo** [comment] 2018-12-03 15:38
Hi subwave07,

Thank you for your reply, I have tried the eclipse plugin on Windows and have finally managed to reproduce the issue.
The problem was with colon character ':' used to separate the file paths. ':' character is required on UNIX, where ';' is required on Windows... Apologies for such a silly mistake.

The plugin is updated:
 * Uninstall the old plugin, and install the new one

Let me know if this fixes the issue for you as well. :)

**Comment by ghost** [comment] 2018-12-04 10:03
Thanks for your fast reply!
Well, tried now to update JUnion plugin, but no improvements after a restart / rebuild

![image](https://user-images.githubusercontent.com/20112417/49434304-2f079480-f7b4-11e8-89b2-872b2bcaad42.jpg)

**Comment by ghost** [comment] 2018-12-04 13:19
Ok, I figured out the problem lookin at your code. Windows uses "\\" separator and this needs to be escaped (as usual for Strings). This problem doesn't happen with Linux/macOS (no need to escape "/")

So we need to write C:\\\Users\\\TehLeo\\\junionc-1.1.jar in order to allow java to read C:\Users\TehLeo\junionc-1.1.jar

**Comment by ghost** [comment] 2018-12-04 14:15
Other problem, yay!

Adding libraries (in this case Gson and Apache Math 3) already inside project directories through "Configure Build Path" > "Add JARs" makes JUnion extremely angry if an import of one of these is specified inside a class.
No problems if you load them using "Configure Build Path" > "Add **External** JARs".
Seems something linked to absolute/relative paths.

https://pastebin.com/09KHpPLk

**Comment by TehLeo** [comment] 2018-12-04 16:00
Thank you for your reply and finding the issue!

I was using java.util.Properties to parse the property file and indeed it did silently drop single '\' characters. This is now fixed in the updated version of the plugin.

Let me know if this finally solves this issue. : )

**Comment by TehLeo** [comment] 2018-12-04 16:03
PS: I'll look into the other issue, it seems the problem with paths is not over yet. ~~It looks like its splitting the paths based on ':' again.~~ 

Edit: The plugin is not translating relative paths to absolute paths. To be updated.

**Comment by TehLeo** [comment] 2018-12-04 20:04
The eclipse plugin is updated. The classpath now correctly translates relative paths to absolute, so jars added with "add jar" and also projects added to classpath work correctly as far as I have tested.

Let me know if this fixes the issues for you as well.

**Comment by reddyalice** [comment] 2018-12-04 22:26
> The eclipse plugin is updated. The classpath now correctly translates relative paths to absolute, so jars added with "add jar" and also projects added to classpath work correctly as far as I have tested.
> 
> Let me know if this fixes the issues for you as well.

OMG thank you it works great now, I am sorry I didn't wanna add something because I assumed I was an idiot and probably doing something wrong ^.^

**Closed as completed** 2018-12-04 22:26 UTC
Labels: bug

**Comment by TehLeo** [comment] 2018-12-04 22:41
Thank you for opening the issue, thanks to you and subwave it got fixed.

If you spot any other/ or would like a new feature, let me know. : )

**Comment by ghost** [comment] 2018-12-05 09:11
Thanks to both of you! (Leo for his quick reply/fix and Kode for raising the problem)

**Comment by ghost** [comment] 2018-12-05 09:42
Ok, updated plugin. Not working again.
A funny fact is that this error happens if I build the project, but disappears if I build it a second time. However, one single edit to my code is equal to 2 rebuilds. Dunno if it has been compiled successfully or not.

https://pastebin.com/wMQ2bq02

**Comment by TehLeo** [comment] 2018-12-05 13:46
Btw the error in your log says:
```
at (TrainModelAction.java:82)theleo.jstruct.plugin.ecj.CompilerError: Multidimensional arrays not implemented.
```
Thus I assume you have tried to use multidimensional arrays.
These are planned to be included in the next version.

Looking at the output you posted, the path "C:\Program Files\Java\jre1.8.0_192\lib\resources.jar"
seems to be split into two paths "C" and "\Program Files\Java\jre1.8.0_192\lib\resources.jar"

Some of the libraries are however still relative. 
How did you include the jars with relative paths such as "junit.jar", "jplasma.jar" into the project?

PS: This time the issue with the path is in the SourceCompiler, thus I might as well implement some features along with the fix.
Thus, I am going to open new topic for version 1.2.1, since this will require fixing junion. You are welcome to suggest new features/found bugs now or once the new version is out.

**Comment by ghost** [comment] 2018-12-05 14:52
> Thus I assume you have tried to use multidimensional arrays.

Yes, in fact I was trying to create a Matrix of structs

> How did you include the jars with relative paths such as "junit.jar", "jplasma.jar" into the project?

I manually added them in a project subfolder and then configured the Build Path with "Add JARs" (relative path), but I'd like to know why they're still referenced during build. That's because they were removed a long time ago; I just checked and no traces or references of them inside the project right now.

**Comment by TehLeo** [comment] 2018-12-05 15:00
Hmm, maybe a clean of the project will remove them? Thou it is still strange they are included in the classpath. This time the classpath is obtained by using eclipse API:

```
AptConfig.getProcessorOptions(project);
```

**Comment by ghost** [comment] 2018-12-05 16:13
Already cleaned, but no change so far; I'll investigate the matter and write here any news regarding this problem.
